### ISSUE TITLE
List of markdown tags available ?

### ISSUE THREAD

**Issue by thiphariel** [njdehoog/swift-hoedown#1]
Hi.

Could you provide a list of Markdown working with your parser ? 

Thanks, I really love it :)

**Comment by njdehoog** [comment]
Hi @thiphariel, swift-hoedown supports everything that [hoedown](https://github.com/hoedown/hoedown) supports, which is this syntax: https://daringfireball.net/projects/markdown/syntax, plus some extensions. See the `HoedownExtensions` for which extensions are supported. You can find examples of a lot of these extensions here: https://help.github.com/articles/github-flavored-markdown/
